# Generated by Django 4.0.2 on 2022-03-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
